"use client";
import Head from "next/head";
import React from "react";
import Register from "./Auth/Register";
import Login from "./Auth/Login";
import OTP from "./Auth/OTP";
import ForgetPassword from "./Auth/ForgetPassword";
import ChangePassword from "./Auth/ChangePassword";
import MainHeader from "./MainHeader";
import MainFooter from "./MainFooter";
import { Inter } from 'next/font/google'
 
const inter = Inter({ subsets: ['latin'] })

export interface IAppProps {}

export default function App({ children }: any) {

  return (
    <>
      <Head>
        <title>Sports Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style jsx global>{`
            body {
              font-family: ${inter.style.fontFamily};
            }
      `}</style>
      </Head>
      <main>
        <MainHeader />
        <div style={{paddingTop:"70px"}}>{children}</div>
        <MainFooter />
        <div id="wrapper">
          <div className="scrollbar" id="style-8">
            <div className="force-overflow"></div>
          </div>
        </div>
        <Register />
        <Login />
        <OTP />
        <ForgetPassword />
        <ChangePassword />
      </main>
    </>
  );
}
